### PR TITLE
[common, desktop] fix #10

### LINKED ISSUE #10: [common] Archive.org broken ($15 bounty - backed)
[Bountysource](https://www.bountysource.com/issues/28378995-common-archive-org-broken?utm_source=28378995&utm_medium=shield&utm_campaign=ISSUE_BADGE)

This should be as simple as taking a look at changes in the JSON output of the Archive.org API and updating our respective objects to match whatever they have changed.

If it's any more complex it could be only because they've changed the REST URL structures and then it's a matter of changing URLs.

```
FrostWire version 6.1.7 build 168
Nov 18, 2015 2:45:50 PM com.frostwire.search.PagedWebSearchPerformer 
INFO: Error searching page: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1011 path $.response.docs[0].subject
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1011 path $.response.docs[0].subject
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(Unknown Source)
at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(Unknown Source)
at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(Unknown Source)
at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(Unknown Source)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(Unknown Source)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(Unknown Source)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(Unknown Source)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(Unknown Source)
at com.google.gson.Gson.fromJson(Unknown Source)
at com.google.gson.Gson.fromJson(Unknown Source)
at com.google.gson.Gson.fromJson(Unknown Source)
at com.google.gson.Gson.fromJson(Unknown Source)
at com.frostwire.util.JsonUtils.toObject(Unknown Source)
at com.frostwire.search.archiveorg.ArchiveorgSearchPerformer.searchPage(Unknown Source)
at com.frostwire.search.PagedWebSearchPerformer.searchPage(Unknown Source)
at com.frostwire.search.PagedWebSearchPerformer.perform(Unknown Source)
at com.frostwire.search.SearchManagerImpl$PerformTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1011 path $.response.docs[0].subject
at com.google.gson.stream.JsonReader.beginArray(Unknown Source)
at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(Unknown Source)
at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(Unknown Source)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(Unknown Source)
... 20 more
```

Perhaps @votaguz or @X-NicON  might want to take a look?

Starting point to look is `at com.frostwire.search.archiveorg.ArchiveorgSearchPerformer.searchPage` and its related classes.

### PR DESCRIPTION
**Pull request by X-NicON**
#10 Archive.org return 'subject' in two different types, in one case String, in another as Array. Field Subject not uses. so I just deleted it.

and seriously for this $ 15? generous reward for such job.

### CODE REVIEW

**Comment by X-NicON** [comment]
Stop. I forgot to remove from the url

**Comment by X-NicON** [comment]
main question. it fits? it solves the problem, but maybe I'm not correctly made

File: desktop/src/com/frostwire/util/filetypes/WinRegistryUtil.java [hunk 1]
```diff
@@ -1049,10 +1049,8 @@ public static void setClassIDByFileExt(String fileExt, String classID, int regLe
             /* If the classID does not exist in the registry table
              * Add it first
              */
-            if (!isSubKeyExist(clsIDKey, regLevel)) {
-                if (clsIDKey != null) {
-                    regCreateKeyEx(clsIDKey, regLevel);
-                }
+            if (clsIDKey != null && !isSubKeyExist(clsIDKey, regLevel)) {
```
Comment (aldenml) [inline desktop/src/com/frostwire/util/filetypes/WinRegistryUtil.java]: Could you revert this change? I rather not touch this file.

Comment (X-NicON) [inline desktop/src/com/frostwire/util/filetypes/WinRegistryUtil.java]: Yes, I understand. my fault that I at first did not understand

**Comment by gubatron** [comment]
Thank you, tested, works now. Change reverted.

**Comment by gubatron** [comment]
Will check now how to release your bounty.

**Comment by gubatron** [comment]
@X-NicON  I think you have to go here and claim the bounty so I can release it

https://www.bountysource.com/issues/28378995-common-archive-org-broken-15-bounty-backed

**Comment by X-NicON** [comment]
Thank You!  Today will be watching a movie with a huge number of chips :)
